- name: Uninstall Docker CLI
  include_tasks: docker.yml
  tags:
  - docker-cli
  - docker

- name: Uninstall Docker Desktop
  include_tasks: docker.yml
  tags:
  - docker-desktop

- name: Uninstall K3s
  include_tasks: k3s.yml
  tags:
  - k3s

- name: Uninstall LibreOffice
  include_tasks: libreoffice.yml
  tags:
  - libreoffice

- name: Uninstall 7Zip
  include_tasks: 7zip.yml
  tags:
  - 7zip
  - 7-zip
  - p7zip
  - p7zip-full
