- name: Install Firefox
  block:
    - name: Install Firefox on Windows
      win_chocolatey:
        name: firefox
        state: latest
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Install Firefox on Debian
      apt:
        name: firefox
        state: latest
      become: true
      when: ansible_os_family == "Debian"
    - name: Install Firefox on RedHat
      yum:
        name: firefox
        state: latest
      become: true
      when: ansible_os_family == "RedHat"
    - name: Install Firefox on MacOS
      homebrew:
        name: firefox
        state: latest
      become: true
      when: ansible_os_family == "Darwin"
    - name: Install Firefox on Alpine
      apk:
        name: firefox
        state: latest
      become: true
      when: ansible_os_family == "Alpine"
  tags: firefox
