- name: Install Chrome
  block:
    - name: Install Chrome on Windows
      win_chocolatey:
        name: googlechrome
        state: latest
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Install Chrome on Debian
      apt:
        name: google-chrome-stable
        state: latest
      become: true
      when: ansible_os_family == "Debian"
    - name: Install Chrome on RedHat
      yum:
        name: google-chrome-stable
        state: latest
      become: true
      when: ansible_os_family == "RedHat"
    - name: Install Chrome on MacOS
      homebrew:
        name: google-chrome
        state: latest
      become: true
      when: ansible_os_family == "Darwin"
    - name: Install Chrome on Alpine
      apk:
        name: chromium
        state: latest
      become: true
      when: ansible_os_family == "Alpine"
  tags: chrome-install

- name: Uninstall Chrome
  block:
    - name: Uninstall Chrome on Windows
      win_chocolatey:
        name: googlechrome
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall Chrome on Debian
      apt:
        name: google-chrome-stable
        state: absent
      become: true
      when: ansible_os_family == "Debian"
    - name: Uninstall Chrome on RedHat
      yum:
        name: google-chrome-stable
        state: absent
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall Chrome on MacOS
      homebrew:
        name: google-chrome
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Uninstall Chrome on Alpine
      apk:
        name: chromium
        state: absent
      become: true
      when: ansible_os_family == "Alpine"
  tags: chrome-uninstall