- name: Uninstall Chrome
  block:
    - name: Uninstall Chrome on Windows
      win_chocolatey:
        name: googlechrome
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall Chrome on Debian
      apt:
        name: google-chrome-stable
        state: absent
      become: true
      when: ansible_os_family == "Debian"
    - name: Remove Chrome repository on Debian
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: absent
        filename: google-chrome
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"
    - name: Remove Chrome repository on RedHat
      yum_repository:
        name: google-chrome
        description: Google Chrome
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        enabled: yes
        gpgcheck: yes
        state: absent
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall Chrome on RedHat
      yum:
        name: google-chrome-stable
        state: absent
      become: true
      when: ansible_os_family == "RedHat"
    - name: Remove Chrome repository on RedHat
      yum_repository:
        name: google-chrome
        description: Google Chrome
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        enabled: yes
        gpgcheck: yes
        state: absent
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall Chrome on MacOS
      homebrew:
        name: google-chrome
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Remove Chrome repository on Alpine
      apk_repository:
        name: google-chrome
        description: Google Chrome
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        enabled: yes
        gpgcheck: yes
        state: absent
      become: true
      when: ansible_os_family == "Alpine"
    - name: Uninstall Chrome on Alpine
      apk:
        name: chromium
        state: absent
      become: true
      when: ansible_os_family == "Alpine"
  tags: chrome