- name: Uninstall Firefox
  block:
    - name: Uninstall Firefox on Windows
      win_chocolatey:
        name: firefox
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall Firefox on Debian
      apt:
        name: firefox
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "Debian"
    - name: Uninstall Firefox on RedHat
      yum:
        name: firefox
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall Firefox on MacOS
      homebrew:
        name: firefox
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Uninstall Firefox on Alpine
      apk:
        name: firefox
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "Alpine"
  tags: firefox