- name: Uninstall git
  block:
    - name: Uninstall git on Windows
      win_chocolatey:
        name: git
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall git on Debian
      apt:
        name: git
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "Debian"
    - name: Uninstall git on RedHat
      yum:
        name: git
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall git on MacOS
      homebrew:
        name: git
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Uninstall git on Alpine
      apk:
        name: git
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "Alpine"
  tags: git
