- name: Uninstall git
  include_tasks: git.yml
  tags:
    - git

- name: Uninstall TortoiseSVN
  include_tasks: tortoisesvn.yml
  tags:
    - tortoisesvn

- name: Uninstall SVN
  include_tasks: svn.yml
  tags:
    - svn
