- name: Uninstall Subversion
  block:
    - name: Uninstall svn on Windows
      win_chocolatey:
        name: svn
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall svn on Debian
      apt:
        name: subversion, libapache2-mod-svn, libsvn-dev, subversion-tools
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "Debian"
    - name: Uninstall svn on RedHat
      yum:
        name: subversion
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall svn on MacOS
      homebrew:
        name: svn
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Uninstall svn on Alpine
      apk:
        name: subversion, apache2, apache2-utils, apache2-webdav, mod_dav_svn
        state: absent
        autoremove: yes
      become: true
      when: ansible_os_family == "Alpine"
  tags: svn
