repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/bin/black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: .venv/bin/flake8
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: .venv/bin/isort
        language: system
        types: [python]
      - id: codespell
        name: codespell
        entry: .venv/bin/codespell
        language: system
        types: [python]
      # - id: pydocstyle
      #   name: pydocstyle
      #   entry: .venv/bin/pydocstyle
      #   language: system
      #   types: [python]