- name: Install Software
  gather_facts: true
  hosts: all
  become: true
  strategy: free
  # tags:
  #   - chrome-install
  #   - firefox-install
  #   - edge-install
  #   - git-install
  #   - tortoisesvn-install
  #   - svn-install
  roles:
    - browsers/install
    # - editors
    - version-control/install
    # - java
    # - nodejs
    # - python
    # - vscode
  