- name: Install Software
  gather_facts: true
  hosts: hosts
  become: true
  strategy: free
  tags:
    - chrome-install
    - firefox-install
    - edge-install
    - git-install
    - tortoisesvn-install
    - svn-install
  roles:
    - browsers
    - editors
    - version-control
    - java
    - nodejs
    - python
    - vscode
  