---
- hosts: all
  tasks:
    - name: Ping all hosts
      ping:
      when: ansible_facts['os_family'] != "Windows"

    - name: Ping all Windows hosts
      environment:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5986
        ansible_winrm_transport: credssp
        ansible_winrm_scheme: https
      win_ping:
      when: ansible_facts['os_family'] == "Windows"