- name: Uninstall Software
  gather_facts: true
  hosts: all
  become: true
  strategy: free
  roles:
    - browsers/uninstall
    - version-control/uninstall
    - languages/uninstall
    - utilities/uninstall
