- name: Uninstall Software
  gather_facts: true
  hosts: hosts
  become: true
  strategy: free
  tags:
    - chrome-uninstall
    - firefox-uninstall
    - edge-uninstall
    - git-uninstall
    - tortoisesvn-uninstall
    - svn-uninstall
  roles:
    - browsers
    - editors
    - version-control
    - java
    - nodejs
    - python
  