- name: Uninstall Software
  gather_facts: true
  hosts: all
  become: true
  strategy: free
  roles:
    - browsers/uninstall
    # - editors
    - version-control/uninstall
    # - java
    # - nodejs
    # - python
