- name: Uninstall Python 3.8
  block:
    - name: Uninstall Python 3.8 on Windows
      win_chocolatey:
        name: python38
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall Python 3.8 on Debian
      apt:
        name: python3.8
        state: absent
      become: true
      when: ansible_os_family == "Debian"
    - name: Uninstall Python 3.8 on RedHat
      yum:
        name: python38
        state: absent
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall Python 3.8 on MacOS
      homebrew:
        name: python@3.8
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Uninstall Python 3.8 on Alpine
      apk:
        name: python3.8
        state: absent
      become: true
      when: ansible_os_family == "Alpine"
  tags:
    - python38
- name: Uninstall Python 3.9
  block:
    - name: Uninstall Python 3.9 on Windows
      win_chocolatey:
        name: python39
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall Python 3.9 on Debian
      apt:
        name: python3.9
        state: absent
      become: true
      when: ansible_os_family == "Debian"
    - name: Uninstall Python 3.9 on RedHat
      yum:
        name: python39
        state: absent
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall Python 3.9 on MacOS
      homebrew:
        name: python@3.9
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Uninstall Python 3.9 on Alpine
      apk:
        name: python3.9
        state: absent
      become: true
      when: ansible_os_family == "Alpine"
  tags:
    - python39
- name: Uninstall Python 3.10
  block:
    - name: Uninstall Python 3.10 on Windows
      win_chocolatey:
        name: python310
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall Python 3.10 on Debian
      apt:
        name: python3.10
        state: absent
      become: true
      when: ansible_os_family == "Debian"
    - name: Uninstall Python 3.10 on RedHat
      yum:
        name: python310
        state: absent
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall Python 3.10 on MacOS
      homebrew:
        name: python@3.10
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Uninstall Python 3.10 on Alpine
      apk:
        name: python3.10
        state: absent
      become: true
      when: ansible_os_family == "Alpine"
  tags:
    - python310
- name: Uninstall Python 3.11
  block:
    - name: Uninstall Python 3.11 on Windows
      win_chocolatey:
        name: python311
        state: absent
      become: true
      become_method: runas
      become_user: "{{ admin_username }}"
      when: ansible_os_family == "Windows"
    - name: Uninstall Python 3.11 on Debian
      apt:
        name: python3.11
        state: absent
      become: true
      when: ansible_os_family == "Debian"
    - name: Uninstall Python 3.11 on RedHat
      yum:
        name: python311
        state: absent
      become: true
      when: ansible_os_family == "RedHat"
    - name: Uninstall Python 3.11 on MacOS
      homebrew:
        name: python@3.11
        state: absent
      become: true
      when: ansible_os_family == "Darwin"
    - name: Uninstall Python 3.11 on Alpine
      apk:
        name: python3.11
        state: absent
      become: true
      when: ansible_os_family == "Alpine"
  tags:
    - python311